import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  introSidebar: [{type: 'autogenerated', dirName: 'introduction'}],
  nodesSidebar: [{type: 'autogenerated', dirName: 'nodes'}],
  miningSidebar: [{type: 'autogenerated', dirName: 'mining'}],
  blockchainSidebar: [{type: 'autogenerated', dirName: 'blockchain'}],
  contractSidebar: [{type: 'autogenerated', dirName: 'contract'}],
  toolsSidebar: [{type: 'autogenerated', dirName: 'tools'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
